map ctrl+shift+left no_op
map ctrl+shift+right no_op

update_check_interval 0

cursor_shape block

font_family Fantasque Sans Mono

bold_font        auto
italic_font      auto
bold_italic_font auto
disable_ligatures always
font_size 14

background #0a0a0a
foreground #ffffff
cursor #39FF14

# ANSI Colors
color0 #01060e
color1 #ea6c73
color2 #39FF14
color3 #ff4140
color4 #00FF9D
color5 #fae944
color6 #00FF9D
color7 #ffffff
color8 #686868
color9 #f07178
color10 #39FF14
color11 #ffb454
color12 #00FF9D
color13 #ffee99
color14 #00FF9D
color15 #ffffff


linux_display_server X11
hide_window_decorations no
shell_integration no-title

tab_powerline_style slanted
tab_bar_style powerline
tab_title_template  "- {index} -"
